"""Add title field to Task db

Revision ID: 40145260acfd
Revises: 00be17f59a4f
Create Date: 2025-09-12 19:13:56.741841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40145260acfd'
down_revision = '00be17f59a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
